### ISSUE TITLE
tcp stealth scan unexpected token error.

### ISSUE THREAD

**Issue by lecramyajiv** [yoramvandevelde/nftables-example#2]
When adding rule for tcp stealth scan with the command 
nft add rule  inet filter input iifname enp2s0 tcp flags & (fin|syn) == (fin|syn) drop
results in  
-bash: syntax error near unexpected token `=='  error. So how do we fix this
Also the following modified commands don't work 
``
 nft add rule  inet filter input iifname enp2s0 tcp flags & fin&syn eq fin&syn drop
this gives the error 
[1] 2673
[2] 2674
[3] 2675
-bash: fin: command not found
-bash: syn: command not found
-bash: syn: command not found
[2]-  Exit 127                fin
[3]+  Exit 127                syn eq fin
 Error: syntax error, unexpected newline
add rule inet filter input iifname enp2s0 tcp flags
                                                   ^
nft add rule  inet filter input iifname enp2s0 tcp flags fin,syn fin,syn drop
Error: syntax error, unexpected comma
add rule inet filter input iifname enp2s0 tcp flags fin,syn fin,syn drop
                                                               ^

 nft add rule  inet filter input iifname enp2s0 tcp flags fin,syn & fin,syn drop
[1] 2678
-bash: fin,syn: command not found

but i do the following command it gets accepted
nft add rule  inet filter input iifname enp2s0 tcp flags fin,syn  drop
[1]+  Done                    nft add rule inet filter input iifname enp2s0 tcp flags fin,syn
is this correct?

**Comment by yoramvandevelde** [comment]
The problem that you encounter has little to do with my ruleset, nftables or the nft command. You are looking at bash processing your rule as a command to the shell itself. 

The problem that you have is that the &, ( and ) are interpreted by your shell as operators. The & as interpreted by your shell means that you want the process forked to the background. As an example try this: 
```
[yoram]#[~] _  sleep 1
[1] 83662
[yoram]#[~] _  ps 83662
  PID   TT  STAT      TIME COMMAND
83662 s000  SN     0:00.00 sleep 10
[yoram]#[~] _
[1]  + done       sleep 10
```

Here we start the command sleep with an argument of 10. This will start a process that sleeps for 10 seconds and then quits. The & at the end tells the shell to fork the process to the background. The printed out **[1] 83662** is the process number. In the example we look at the process with **ps**. After 10 seconds we get a message that sleep is done and has quit.

Now for the output you have pasted in your question:
```
nft add rule inet filter input iifname enp2s0 tcp flags & fin&syn eq fin&syn drop
this gives the error
[1] 2673
[2] 2674
[3] 2675
```

The first line is interpreted by bash as follows:
1. start the command **nft add rule inet filter input iifname enp2s0 tcp flags** and fork it to the background. This process gets process ID 2673
2. start the command **fin** and fork it to the background. This process gets process ID 2674
3. start the command **syn eq fin** and fork ik to the background. This process gets process ID 2675.

You might need to put your rule between quotes for this to work. More information on forking in bash can be found on https://bashitout.com/2013/05/18/Ampersands-on-the-command-line.html
