### ISSUE TITLE
"add @blacklist ..." is missing

### ISSUE THREAD

**Issue by szazs89** [yoramvandevelde/nftables-example#3]
isn't it?
(I mean, how/where is it populated with IP addresses)
-- Zsolt

**Comment by yoramvandevelde** [comment]
Thanks for the comment. The idea in this script was to define the set and use it, not to populate it from within this ruleset.
Personally I made this to play around with it and use it in fail2ban. I would add ip's via the command line to the defined like so:

`nft add element ip filter blackhole { 192.168.1.4, 192.168.1.5 }`

Does this make sense?

**Comment by szazs89** [comment]
Oh, I see. Thank you!
(Maybe this should be in a comment somewhere... or I missed it.)
Regards, Zsolt

-----Original Message-----

**Comment by yoramvandevelde** [comment]
Added comment to explain this in 315f8e6
